name: project__actions
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: python -m unittest
    clean:
        runs-on: ubuntu-latest
        steps:
            - run: find . | grep -E "__pycache__" | xargs rm -rf
